aws_access_key_id = "ASIASEPGD37DYPJEAXF4"
aws_secret_access_key = "SYEwqRp0YYBSxXURxuWIInmU5cmFs/EhO+raGvHc"
aws_session_token = "FwoGZXIvYXdzEKb//////////wEaDCeBM6Qw4P+Na0DdNSLNAQGl2RSuuLc0a0GdjhjArfdNQf6WTbof42cfISQsbtylKqYhOaxhqTg4kmWv6W3F8aeR4gSJe8rtfeXE3ufh+Bv/DVoFwuNsUJWrgYfLPHtWtI0UCDMNdzmSgLCiwcOwL9IVTAd5+SMHkL2r5ziwo+y1BdtXOdLObIYfHu+rOs4ZbvTZuuYD/3ClgcYQ8uu40/p+jR4a44xlyiY21OmBB/iEmBCjv+KRTROCw5uziNTY3w/5uyeRy7LROn7qqzt58VfzJiMYgF80jrE+6ekonLvMoQYyLXyYp7cCQ86iwCAJGkQzGv/CIJJ9OIWJQgUHLMcehLjMefrs0FRsncT5EZfSiA=="
region_name = "us-east-1"
